[package]
name          = "amq-protocol"
version       = "2.0.0-rc16" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP 0.9 specifications"
repository    = "https://github.com/sozu-proxy/amq-protocol"
documentation = "https://docs.rs/amq-protocol"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
build         = "build.rs"

[lib]
name = "amq_protocol"

[features]
default        = ["native-tls"]
native-tls     = ["amq-protocol-tcp/native-tls"]
openssl        = ["amq-protocol-tcp/openssl"]
rustls         = ["amq-protocol-tcp/rustls"]
tokio          = ["amq-protocol-tcp/tokio"]
verbose-errors = ["amq-protocol-types/verbose-errors"]

[build-dependencies.amq-protocol-codegen]
version = "=2.0.0-rc16"
path    = "../codegen"

[dependencies]
cookie-factory = "=0.3.0-beta2"
nom            = "=5.0.0-beta2"

[dependencies.amq-protocol-tcp]
version          = "=2.0.0-rc16"
default-features = false
path             = "../tcp"

[dependencies.amq-protocol-types]
version = "=2.0.0-rc16"
path    = "../types"

[dependencies.amq-protocol-uri]
version = "=2.0.0-rc16"
path    = "../uri"

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
