[package]
name          = "amq-protocol-tcp"
version       = "2.0.0-rc16" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP 0.9 URI TCP connection handling"
repository    = "https://github.com/sozu-proxy/amq-protocol"
documentation = "https://docs.rs/amq-protocol-tcp"
keywords      = ["amqp","rabbitmq","protocol"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "amq_protocol_tcp"

[features]
default    = ["native-tls"]
native-tls = ["tcp-stream/native-tls"]
openssl    = ["tcp-stream/openssl"]
rustls     = ["tcp-stream/rustls"]
tokio      = ["tcp-stream/tokio"]

[dependencies.amq-protocol-uri]
version = "=2.0.0-rc16"
path    = "../uri"

[dependencies.tcp-stream]
version          = "^0.2"
default-features = false

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
